on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Card Test
        uses: ./
        id: test
        with:
          version: 1
          contributor: Jake
          description: this is a description
