on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Read release text
        run: echo "::set-output name=value::$(cat RELEASE.md)"
        id: description
      - name: Create Card Test
        uses: ./
        with:
          version: 1.0
          contributor: Jake
          description: ${{ steps.description.value }}

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: screenshot.png
          path: screenshot.png 
          retention-days: 5
