on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Card Test
        uses: ./
        id: test
        with:
          version: 1
          contributor: Jake
          description: |
            This a super **cool** release.

            [aaa](http://google.com)

            - a list
            - a list

            Awesome.


      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: screenshot.png
          path: screenshot.png 
          retention-days: 5
